#!/usr/bin/env python3
import argparse
import datetime as dt
import decimal
import sqlite3
from pathlib import Path


TABLES = {
    "ContasFinanceiras": {
        "columns": [
            ("Id", "integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("Nome", "varchar(120) NOT NULL"),
            ("Instituicao", "varchar(120) NOT NULL"),
            ("Tipo", "integer NOT NULL"),
            ("SaldoInicial", "numeric(18,2) NOT NULL"),
            ("Ativa", "boolean NOT NULL"),
            ("CriadaEm", "timestamp without time zone NOT NULL"),
        ],
        "bools": {"Ativa"},
    },
    "Categorias": {
        "columns": [
            ("Id", "integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("Nome", "varchar(120) NOT NULL"),
            ("Tipo", "integer NOT NULL"),
            ("Cor", "varchar(20) NOT NULL"),
            ("Ativa", "boolean NOT NULL"),
        ],
        "bools": {"Ativa"},
    },
    "ReceitasMensais": {
        "columns": [
            ("Id", "integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("Descricao", "varchar(160) NOT NULL"),
            ("Valor", "numeric(18,2) NOT NULL"),
            ("Mes", "integer NOT NULL"),
            ("Ano", "integer NOT NULL"),
        ],
        "indexes": [
            'CREATE UNIQUE INDEX IF NOT EXISTS "IX_ReceitasMensais_Ano_Mes_Descricao" ON {table} ("Ano", "Mes", "Descricao");'
        ],
    },
    "LancamentosCartaoCredito": {
        "columns": [
            ("Id", "integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("Descricao", "varchar(180) NOT NULL"),
            ("Cartao", "varchar(120) NOT NULL"),
            ("ValorTotal", "numeric(18,2) NOT NULL"),
            ("QuantidadeParcelas", "integer NOT NULL"),
            ("MesInicial", "integer NOT NULL"),
            ("AnoInicial", "integer NOT NULL"),
            ("Observacao", "varchar(500) NULL"),
            ("CriadoEm", "timestamp without time zone NOT NULL"),
        ],
    },
    "FaturasCartaoCredito": {
        "columns": [
            ("Id", "integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("Cartao", "varchar(120) NOT NULL"),
            ("ValorTotal", "numeric(18,2) NOT NULL"),
            ("Mes", "integer NOT NULL"),
            ("Ano", "integer NOT NULL"),
            ("Vencimento", "timestamp without time zone NULL"),
            ("Observacao", "varchar(500) NULL"),
        ],
        "indexes": [
            'CREATE UNIQUE INDEX IF NOT EXISTS "IX_FaturasCartaoCredito_Cartao_Ano_Mes" ON {table} ("Cartao", "Ano", "Mes");'
        ],
    },
    "Orcamentos": {
        "columns": [
            ("Id", "integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("Nome", "varchar(120) NOT NULL"),
            ("Mes", "integer NOT NULL"),
            ("Ano", "integer NOT NULL"),
            ("ValorPlanejado", "numeric(18,2) NOT NULL"),
            ("CategoriaId", "integer NOT NULL"),
        ],
        "foreign_keys": [
            'ALTER TABLE {table} ADD CONSTRAINT "FK_Orcamentos_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES {schema_table_categorias} ("Id") ON DELETE RESTRICT;'
        ],
        "indexes": [
            'CREATE INDEX IF NOT EXISTS "IX_Orcamentos_CategoriaId" ON {table} ("CategoriaId");'
        ],
    },
    "Transacoes": {
        "columns": [
            ("Id", "integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"),
            ("Descricao", "varchar(180) NOT NULL"),
            ("Valor", "numeric(18,2) NOT NULL"),
            ("Data", "timestamp without time zone NOT NULL"),
            ("Tipo", "integer NOT NULL"),
            ("Efetivada", "boolean NOT NULL"),
            ("Observacao", "varchar(500) NULL"),
            ("ContaFinanceiraId", "integer NOT NULL"),
            ("CategoriaId", "integer NOT NULL"),
        ],
        "bools": {"Efetivada"},
        "foreign_keys": [
            'ALTER TABLE {table} ADD CONSTRAINT "FK_Transacoes_ContasFinanceiras_ContaFinanceiraId" FOREIGN KEY ("ContaFinanceiraId") REFERENCES {schema_table_contas} ("Id") ON DELETE RESTRICT;',
            'ALTER TABLE {table} ADD CONSTRAINT "FK_Transacoes_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES {schema_table_categorias} ("Id") ON DELETE RESTRICT;',
        ],
        "indexes": [
            'CREATE INDEX IF NOT EXISTS "IX_Transacoes_ContaFinanceiraId" ON {table} ("ContaFinanceiraId");',
            'CREATE INDEX IF NOT EXISTS "IX_Transacoes_CategoriaId" ON {table} ("CategoriaId");',
        ],
    },
}

TABLE_ORDER = [
    "ContasFinanceiras",
    "Categorias",
    "ReceitasMensais",
    "LancamentosCartaoCredito",
    "FaturasCartaoCredito",
    "Orcamentos",
    "Transacoes",
]


def quote_ident(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def qualify(schema: str, table: str) -> str:
    return f"{quote_ident(schema)}.{quote_ident(table)}"


def sql_value(value, column: str, table: str) -> str:
    if value is None:
        return "NULL"

    if column in TABLES[table].get("bools", set()):
        return "TRUE" if int(value) else "FALSE"

    if isinstance(value, (int, float, decimal.Decimal)):
        return str(value)

    text = str(value)
    if column in {"CriadaEm", "Data", "CriadoEm", "Vencimento"}:
        text = text.replace("T", " ")
        if text.endswith("Z"):
            text = text[:-1]
        try:
            text = dt.datetime.fromisoformat(text).strftime("%Y-%m-%d %H:%M:%S")
        except ValueError:
            pass

    return "'" + text.replace("'", "''") + "'"


def table_exists(connection: sqlite3.Connection, table: str) -> bool:
    cursor = connection.execute(
        "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?",
        (table,),
    )
    return cursor.fetchone() is not None


def create_table_sql(schema: str, table: str) -> list[str]:
    definition = TABLES[table]
    columns = ",\n    ".join(f"{quote_ident(name)} {sql_type}" for name, sql_type in definition["columns"])
    return [f"CREATE TABLE IF NOT EXISTS {qualify(schema, table)} (\n    {columns}\n);"]


def insert_sql(connection: sqlite3.Connection, schema: str, table: str) -> list[str]:
    if not table_exists(connection, table):
        return []

    definition = TABLES[table]
    columns = [name for name, _ in definition["columns"]]
    quoted_columns = ", ".join(quote_ident(column) for column in columns)
    update_columns = [column for column in columns if column != "Id"]
    update_sql = ", ".join(f"{quote_ident(column)} = EXCLUDED.{quote_ident(column)}" for column in update_columns)
    rows = connection.execute(
        f"SELECT {', '.join(quote_ident(column) for column in columns)} FROM {quote_ident(table)} ORDER BY \"Id\""
    ).fetchall()

    statements = []
    for row in rows:
        values = ", ".join(sql_value(row[column], column, table) for column in columns)
        statements.append(
            f"INSERT INTO {qualify(schema, table)} ({quoted_columns}) VALUES ({values}) "
            f"ON CONFLICT ({quote_ident('Id')}) DO UPDATE SET {update_sql};"
        )

    if rows:
        statements.append(
            f"SELECT setval(pg_get_serial_sequence('{quote_ident(schema)}.{quote_ident(table)}', 'Id'), "
            f"COALESCE((SELECT MAX({quote_ident('Id')}) FROM {qualify(schema, table)}), 1), true);"
        )

    return statements


def constraint_exists(schema: str, constraint: str) -> str:
    safe_schema = schema.replace("'", "''")
    safe_constraint = constraint.replace("'", "''")
    return (
        "NOT EXISTS ("
        "SELECT 1 FROM pg_constraint c "
        "JOIN pg_namespace n ON n.oid = c.connamespace "
        f"WHERE n.nspname = '{safe_schema}' "
        f"AND c.conname = '{safe_constraint}'"
        ")"
    )


def foreign_key_sql(schema: str, table: str) -> list[str]:
    definition = TABLES[table]
    statements = []
    replacements = {
        "table": qualify(schema, table),
        "schema_table_categorias": qualify(schema, "Categorias"),
        "schema_table_contas": qualify(schema, "ContasFinanceiras"),
    }
    for template in definition.get("foreign_keys", []):
        sql = template.format(**replacements)
        constraint = sql.split('CONSTRAINT "', 1)[1].split('"', 1)[0]
        statements.append(
            "DO $$ BEGIN\n"
            f"    IF {constraint_exists(schema, constraint)} THEN\n"
            f"        {sql}\n"
            "    END IF;\n"
            "END $$;"
        )
    return statements


def index_sql(schema: str, table: str) -> list[str]:
    replacements = {"table": qualify(schema, table)}
    return [template.format(**replacements) for template in TABLES[table].get("indexes", [])]


def main():
    parser = argparse.ArgumentParser(description="Exporta o SQLite local para SQL compativel com Supabase/Postgres.")
    parser.add_argument("--sqlite", default="financeiro.db", help="Caminho do banco SQLite local.")
    parser.add_argument("--schema", required=True, help="Schema destino no Supabase/Postgres.")
    parser.add_argument("--output", default="artifacts/supabase-migration.sql", help="Arquivo SQL de saida.")
    args = parser.parse_args()

    sqlite_path = Path(args.sqlite)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    connection = sqlite3.connect(sqlite_path)
    connection.row_factory = sqlite3.Row

    lines = [
        "-- Migracao gerada a partir do SQLite local.",
        "-- Revise antes de executar no Supabase.",
        "BEGIN;",
        f"CREATE SCHEMA IF NOT EXISTS {quote_ident(args.schema)};",
    ]

    for table in TABLE_ORDER:
        lines.extend(create_table_sql(args.schema, table))

    for table in TABLE_ORDER:
        lines.extend(index_sql(args.schema, table))

    for table in TABLE_ORDER:
        lines.extend(foreign_key_sql(args.schema, table))

    for table in TABLE_ORDER:
        lines.extend(insert_sql(connection, args.schema, table))

    lines.append("COMMIT;")
    output_path.write_text("\n\n".join(lines) + "\n", encoding="utf-8")
    print(f"SQL gerado em: {output_path}")


if __name__ == "__main__":
    main()
